# Generated by Django 5.2.6 on 2025-09-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Content',
            new_name='content',
        ),
    ]
