# Generated by Django 5.2.6 on 2025-09-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_note_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
